spring:
  application:
    name: USER-SERVICE

eureka:
  client:
    service-url:
#      defaultZone : http://service-registry:8761/eureka/
      defaultZone : http://localhost:8761/eureka/


server:
  port: 8005